config/routes.rb
PhcdevworksMembers::Engine.routes.draw do

  # Dashboard Routes
  get 'dashboard', to: 'info/dashboard#index'

  # Member Routes
  namespace :member do
    resources :profiles, class_name: 'Member::Profile' do
      resources :listings, class_name: 'Member::Listing'
      resources :addresses, class_name: 'Member::Address'
    end
  end

  # Directory Routes
  namespace :directory do
    resources :categories, class_name: 'Directory::Category'
  end

  # API Routes
  namespace :api, :path => "", :constraints => {:subdomain => "api"} do
    namespace :v1 do
        resources :categories, defaults: {format: 'json'} do
        resources :listings, defaults: {format: 'json'}
      end
    end
  end

  # Mount Routes
  mount PhcdevworksAccounts::Engine, :at => '/'
  mount PhcdevworksCoreModules::Engine, :at => '/'

end

app/models/phcdevworks_members/member.rb
module PhcdevworksMembers
  module Member
    def self.table_name_prefix
      'phcdevworks_members_member_'
    end
  end
end

app/models/phcdevworks_members/member/address.rb
module PhcdevworksMembers
  class Member::Address < ApplicationRecord

    # Clean URL Initialize
    extend FriendlyId

    # Paper Trail Initialize
    has_paper_trail :class_name => 'PhcdevworksMembers::MemberAddressVersions'

    # Relationships
    belongs_to :profile, class_name: 'PhcdevworksMembers::Member::Profile'

    # Form Fields Validation
    validates :member_address_line_1,
      presence: true

    validates :member_address_city,
      presence: true

    validates :member_address_province,
      presence: true

    validates :member_address_country,
      presence: true

    validates :member_address_postal_code,
      presence: true

    # Clean URL Define
    friendly_id :members_address_nice_urls, use: [:slugged, :finders]

    def members_address_nice_urls
      [
        [:member_address_type, :member_address_city, :member_address_province]
      ]
    end

  end
end

app/models/phcdevworks_members/member/listing.rb
module PhcdevworksMembers
  class Member::Listing < ApplicationRecord

    # Clean URL Initialize
    extend FriendlyId

    # Paper Trail Initialize
    has_paper_trail :class_name => "PhcdevworksMembers::MemberListingVersions"

    # Relationships
    belongs_to :profile, class_name: "PhcdevworksMembers::Member::Profile"
    belongs_to :optimization, class_name: "PhcdevworksCoreModules::Marketing::Optimization", optional: true
    has_and_belongs_to_many :categories, class_name: "PhcdevworksMembers::Directory::Category", :join_table => "phcdevworks_members_categories_lstings", :dependent => :destroy

    # Form Fields Validation
    validates :member_listing_company_name,
      presence: true

    validates :member_listing_contact_name,
      presence: true

    validates :member_listing_address_line_1,
      presence: true

    validates :member_listing_city,
      presence: true

    validates :member_listing_country,
      presence: true

    validates :member_listing_province,
      presence: true

    validates :member_listing_postal_code,
      presence: true

    validates :member_listing_contact_email,
      presence: true,
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Please follow this Email format: *****@********.***" }

    validates :member_listing_website,
      presence: true,
      format: { with: URI::regexp(%w(http https)), message: "Please follow this URL format http or https://www.**********.com" }

    validates :member_listing_phone,
      presence: true,
      format: { with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "Please Follow this Phone Member Format: ***-***-****" }

    # Clean URL Define
    friendly_id :members_listing_nice_urls, use: [:slugged, :finders]

    def members_listing_nice_urls
      [
        [:member_listing_company_name, :member_listing_contact_name]
      ]
    end

  end
end

app/models/phcdevworks_members/member/profile.rb
module PhcdevworksMembers
  class Member::Profile < ApplicationRecord

    # Clean URL Initialize
    extend FriendlyId

    # Paper Trail Initialize
    has_paper_trail :class_name => 'PhcdevworksMembers::MemberProfileVersions'

    # Profile Gravatar
    include Gravtastic
      gravtastic :member_profile_email

    # Relationships
    has_many :addresses, class_name: 'Member::Address', :dependent => :destroy
    has_many :listings, class_name: 'Member::Listing', :dependent => :destroy

    # Form Fields Validation
    validates :member_profile_first_name,
      presence: true

    validates :member_profile_last_name,
      presence: true

    validates :member_profile_title,
      presence: true

    validates :member_profile_email,
      presence: true,
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Please follow this Email format: *****@********.***" }

    validates :member_profile_phone,
      presence: true,
      format: { with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "Please Follow this Phone Number Format: ***-***-****" }

    # Clean URL Define
    friendly_id :members_profile_nice_urls, use: [:slugged, :finders]

    def members_profile_nice_urls
      [
        [:member_profile_first_name, :member_profile_last_name]
      ]
    end

  end
end

app/controllers/phcdevworks_members/member/addresses_controller.rb
require_dependency "phcdevworks_members/application_controller"

module PhcdevworksMembers
  class Member::AddressesController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_member_address, only: [:show, :edit, :update, :destroy]

    # GET /member/addresses
    # GET /member/addresses.json
    def index
      @member_addresses = member_profile.addresses.all
    end

    # GET /member/addresses/1
    # GET /member/addresses/1.json
    def show
      @member_address = member_profile.addresses.find(params[:id])
      @member_address_versions = PhcdevworksMembers::MemberAddressVersions.where(item_id: @member_address, item_type: 'PhcdevworksMembers::Member::Address')
    end

    # GET /member/addresses/new
    def new
      @member_address = member_profile.addresses.build
    end

    # GET /member/addresses/1/edit
    def edit
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
    end

    # POST /member/addresses
    # POST /member/addresses.json
    def create
      @member_address = member_profile.addresses.create(member_address_params)
      @member_address.user_id = current_user.id
      @member_address.org_id = current_user.org_id
      respond_to do |format|
        if @member_address.save
          format.html { redirect_to member_profile_addresses_url, :flash => { :success => 'Member Address has been Added' }}
          format.json { render :show, status: :created, location: @member_address }
        else
          format.html { render :new }
          format.json { render json: @member_address.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /member/addresses/1
    # PATCH/PUT /member/addresses/1.json
    def update
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
      respond_to do |format|
        if @member_address.update(member_address_params)
          format.html { redirect_to member_profile_addresses_url, :flash => { :notice => 'Member Address has been Updated.' }}
          format.json { render :show, status: :ok, location: @member_address }
        else
          format.html { render :edit }
          format.json { render json: @member_address.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /member/addresses/1
    # DELETE /member/addresses/1.json
    def destroy
      @member_address = member_profile.addresses.find(params[:id])
      @member_address.destroy
      respond_to do |format|
        format.html { redirect_to member_profile_addresses_url, :flash => { :error => 'Member Address has been Removed' }}
        format.json { head :no_content }
      end
    end

    private

    # Common Callbacks
    def set_member_address
      @member_address = Member::Address.friendly.find(params[:id])
    end

    def member_profile
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
    end

    # Whitelist
    def member_address_params
      params.require(:member_address).permit(:member_address_line_1, :member_address_line_2, :member_address_city, :member_address_province, :member_address_country, :member_address_postal_code, :member_address_type, :profile_id, :slug, :user_id, :org_id)
    end

  end
end

app/controllers/phcdevworks_members/member/dashboard_controller.rb
require_dependency "phcdevworks_members/application_controller"

module PhcdevworksMembers
  class Member::DashboardController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!

    # Index
    def index
      @member_profile_dashboard = PhcdevworksMembers::Member::Profile.all
      @member_listing_dashboard = PhcdevworksMembers::Member::Listing.all
      @member_address_dashboard = PhcdevworksMembers::Member::Address.all
      @directory_category_dashboard = PhcdevworksMembers::Directory::Category.all
    end

  end
end

app/controllers/phcdevworks_members/member/listings_controller.rb
require_dependency "phcdevworks_members/application_controller"

module PhcdevworksMembers
  class Member::ListingsController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_member_listing, only: [:show, :edit, :update, :destroy]

    # GET /member/listings
    # GET /member/listings.json
    def index
      @member_listings = member_profile.listings.all
    end

    # GET /member/listings/1
    # GET /member/listings/1.json
    def show
      @meber_listing = member_profile.listings.find(params[:id])
      @member_listing_versions = PhcdevworksMembers::MemberListingVersions.where(item_id: @member_listing, item_type: 'PhcdevworksMembers::Member::Listing')
    end

    # GET /member/listings/new
    def new
      @member_listing = member_profile.listings.build
    end

    # GET /member/listings/1/edit
    def edit
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
    end

    # POST /member/listings
    # POST /member/listings.json
    def create
      @member_listing = member_profile.listings.create(member_listing_params)
      @member_listing.user_id = current_user.id
      @member_listing.org_id = current_user.org_id
      respond_to do |format|
        if @member_listing.save
          format.html { redirect_to member_profile_listings_url, :flash => { :success => 'Member Listing has been Added' }}
          format.json { render :show, status: :created, location: @member_listing }
        else
          format.html { render :new }
          format.json { render json: @member_listing.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /member/listings/1
    # PATCH/PUT /member/listings/1.json
    def update
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
      respond_to do |format|
        if @member_listing.update(member_listing_params)
          format.html { redirect_to member_profile_listings_url, :flash => { :notice => 'Member Listing has been Updated.' }}
          format.json { render :show, status: :ok, location: @member_listing }
        else
          format.html { render :edit }
          format.json { render json: @member_listing.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /member/listings/1
    # DELETE /member/listings/1.json
    def destroy
      @member_listing = member_profile.listings.find(params[:id])
      @member_listing.destroy
      respond_to do |format|
        format.html { redirect_to member_profile_listings_url, :flash => { :error => 'Member Listing has been Removed' }}
        format.json { head :no_content }
      end
    end

    private

    # Common Callbacks
    def set_member_listing
     @member_listing = Member::Listing.friendly.find(params[:id])
    end

    def member_profile
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
    end

    # Whitelist
    def member_listing_params
      params.require(:member_listing).permit(:member_listing_company_name, :member_listing_contact_name, :member_listing_address_line_1, :member_listing_address_line_2, :member_listing_city, :member_listing_country, :member_listing_province, :member_listing_postal_code, :member_listing_phone, :member_listing_contact_email, :member_listing_website, :profile_id, :slug, :user_id, :org_id, category_ids: [])
    end

  end
end

app/controllers/phcdevworks_members/member/profiles_controller.rb
require_dependency "phcdevworks_members/application_controller"

module PhcdevworksMembers
  class Member::ProfilesController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_member_profile, only: [:show, :edit, :update, :destroy]
    layout "phcdevworks_members/member_profile", :only => [ :show ]

    # GET /member/profiles
    # GET /member/profiles.json
    def index
      @member_profiles = Member::Profile.all
    end

    # GET /member/profiles/1
    # GET /member/profiles/1.json
    def show
      @member_profile_versions = PhcdevworksMembers::MemberProfileVersions.where(item_id: @member_profile, item_type: 'PhcdevworksMembers::Member::Profile')
    end

    # GET /member/profiles/new
    def new
      @member_profile = Member::Profile.new
    end

    # GET /member/profiles/1/edit
    def edit
    end

    # POST /member/profiles
    # POST /member/profiles.json
    def create
      @member_profile = Member::Profile.new(member_profile_params)
      @member_profile.user_id = current_user.id
      @member_profile.org_id = current_user.org_id
      respond_to do |format|
        if @member_profile.save
          format.html { redirect_to @member_profile, :flash => { :success => 'Member Profile has been Added.' }}
          format.json { render :show, status: :created, location: @member_profile }
        else
          format.html { render :new }
          format.json { render json: @member_profile.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /member/profiles/1
    # PATCH/PUT /member/profiles/1.json
    def update
      respond_to do |format|
        if @member_profile.update(member_profile_params)
          format.html { redirect_to @member_profile, :flash => { :notice => 'Member Profile has been Updated.' }}
          format.json { render :show, status: :ok, location: @member_profile }
        else
          format.html { render :edit }
          format.json { render json: @member_profile.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /member/profiles/1
    # DELETE /member/profiles/1.json
    def destroy
      @member_profile.destroy
      respond_to do |format|
        format.html { redirect_to member_profiles_url, :flash => { :error => 'Member Profile, Listings and Addresses have all been Removed.' }}
        format.json { head :no_content }
      end
    end

    private

    # Common Callbacks
    def set_member_profile
      @member_profile = Member::Profile.friendly.find(params[:id])
    end

    # Whitelist
    def member_profile_params
      params.require(:member_profile).permit(:member_profile_first_name, :member_profile_last_name, :member_profile_title, :member_profile_email, :member_profile_phone, :member_profile_notes, :slug, :user_id, :org_id)
    end

  end
end

app/helpers/phcdevworks_members/member/addresses_helper.rb
module PhcdevworksMembers
  module Member::AddressesHelper
  end
end

app/helpers/phcdevworks_members/member/dashboard_helper.rb
module PhcdevworksMembers
  module Member::DashboardHelper
  end
end

app/helpers/phcdevworks_members/member/listings_helper.rb
module PhcdevworksMembers
  module Member::ListingsHelper
  end
end

app/helpers/phcdevworks_members/member/profiles_helper.rb
module PhcdevworksMembers
  module Member::ProfilesHelper
  end
end

app/views/phcdevworks_members/member/addresses/_form.html.erb
<!-- Form - Member - Addresses -->
<%= form_with(model: [ @member_profile, @member_address], url: form_url, local: true) do |form| %>

	<!-- PHCNotifi Render Validation -->
	<%= render "phcdevworks_notifications/bootstrap/validations", :object => @member_address %>
	<!-- PHCNotifi Render Validation -->

	<!-- Form Input Fields -->
	<div class="form-group field_with_errors">
		<%= form.label :member_address_line_1, "Address Line1" %>
		<%= form.text_field :member_address_line_1, placeholder: "Address Line 1 - Street Address", class: "form-control" %>
	</div>

	<div class="form-group field_with_errors">
		<%= form.label :member_address_line_2, "Address Line2" %>
		<%= form.text_field :member_address_line_2, placeholder: "Address Line 2 - Box - Suite - Floor", class: "form-control" %>
	</div>

	<div class="form-group field_with_errors">
		<%= form.label :member_address_city, "City" %>
		<%= form.text_field :member_address_city, placeholder: "City", class: "form-control" %>
	</div>

	<div class="form-group field_with_errors">
		<%= form.label :member_address_province, "Province/State" %>
		<%= form.text_field :member_address_province, placeholder: "Province/State", class: "form-control" %>
	</div>

	<div class="form-group field_with_errors">
		<%= form.label :member_address_country, "Country" %>
		<%= form.text_field :member_address_country, placeholder: "Country", class: "form-control" %>
	</div>

	<div class="form-group field_with_errors">
		<%= form.label :member_address_postal_code, "PostalCode" %>
		<%= form.text_field :member_address_postal_code, placeholder: "PostalCode", class: "form-control" %>
	</div>

	<div class="form-group field_with_errors">
		<%= form.label :member_address_type, "Address Type" %>
		<%= form.select( :member_address_type, [["Billing Address","Billing"],["Street Address","Street"],["Mailing Address","Mailing"],["Home Address","Home"],["Business Address","Business"]], {}, {class: "form-control"}) %>
	</div>
	<!-- Form Input Fields -->

	<!-- Form Submition Button -->
	<div class="actions">
		<%= form.submit class: "btn btn-primary" %>
	</div>
	<!-- For Submition Button -->

<% end %>
<!-- Form - Member - Addresses -->

app/views/phcdevworks_members/member/addresses/edit.html.erb
<!-- PHCTitleSEO Title Variables -->
<% phc_title "Member Address Manager" %>
<% phc_title_tagline "Update New Address for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name %>
<% phc_breadcrumb_one link_to "Members List", phcdevworks_members.member_profiles_path %>
<% phc_breadcrumb_two link_to "Addresses for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name, phcdevworks_members.member_profile_addresses_path %>
<% phc_breadcrumb_three yield(:phc_title_tagline) %>
<!-- PHCTitleSEO Title Variables -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_two) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_three) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h2 class="page-header"><%= yield(:phc_title) %></h2>
<!-- Page Header -->

<!-- Page Content -->
<div class="row">
	<div class="col-lg-12">

		<!-- Panel -->
		<div class="panel panel-inverse">

			<!-- Panel - Heading -->
			<div class="panel-heading">
				<h4 class="panel-title"><%= yield(:phc_title) %></h4>
			</div>
			<!-- Panel - Heading -->

			<!-- Panel - Body -->
			<div class="panel-body">

				<!-- Edit Form -->
				<%= render "form", { form_url: member_profile_address_path } %>
				<!-- Edit Form -->

			</div>
			<!-- Panel - Body -->

		</div>
		<!-- Panel -->

	</div>
</div>
<!-- Page Content -->

app/views/phcdevworks_members/member/addresses/index.html.erb
<!-- PHCTitleSEO Title Variables -->
<% phc_title "Member Address Manager" %>
<% phc_title_tagline "Addresses for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name %>
<% phc_breadcrumb_one link_to "Members List", phcdevworks_members.member_profiles_path %>
<% phc_breadcrumb_two link_to @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name + " Details", phcdevworks_members.member_profile_path(@member_profile) %>
<% phc_breadcrumb_three yield(:phc_title_tagline) %>
<!-- PHCTitleSEO Title Variables -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_two) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_three) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h2 class="page-header"><%= yield(:phc_title) %></h2>
<!-- Page Header -->

<!-- Page Content -->
<div class="row">
	<div class="col-lg-12">

		<!-- Panel -->
		<div class="panel panel-inverse">

			<!-- Panel - Heading -->
			<div class="panel-heading">
				<h4 class="panel-title"><%= yield(:phc_title) %></h4>
			</div>
			<!-- Panel - Heading -->

			<!-- Panel - Body -->
			<div class="panel-body">

				<!-- Index - Table -->
				<div class="table-responsive">
					<table class="table table-striped table-bordered">

						<thead>
							<tr>
								<th>Address Line 1</th>
								<th>City</th>
								<th>Country</th>
								<th>PostalCode</th>
								<th>Type</th>
								<th></th>
							</tr>
						</thead>

						<tbody>
							<% @member_addresses.each do |member_address| %>
								<tr>
									<td><%= link_to member_address.member_address_line_1, phcdevworks_members.member_profile_address_path(member_address.profile, member_address) %></td>
									<td><%= link_to member_address.member_address_city, phcdevworks_members.member_profile_address_path(member_address.profile, member_address) %></td>
									<td><%= link_to member_address.member_address_country, phcdevworks_members.member_profile_address_path(member_address.profile, member_address) %></td>
									<td><%= link_to member_address.member_address_postal_code, phcdevworks_members.member_profile_address_path(member_address.profile, member_address) %></td>
									<td><%= link_to member_address.member_address_type, phcdevworks_members.member_profile_address_path(member_address.profile, member_address) %></td>
									<td>
										<div class="btn-group d-flex" role="group">
											<%= link_to "Address Details", member_profile_address_path(member_address.profile, member_address), class: "btn btn-primary btn-xs" %>
											<%= link_to "Update Address", edit_member_profile_address_path(member_address.profile, member_address), class: "btn btn-purple btn-xs" %>
											<%= link_to "Remove Address", member_profile_address_path(member_address.profile, member_address), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure? This will remove listing information and cannot be reversed." } %>
										</div>
									</td>
								</tr>
							<% end %>
						</tbody>

					</table>
				</div>
				<!-- Index - Table -->

				<!-- New Button -->
				<%= link_to phcdevworks_members.new_member_profile_address_path, class: "btn btn-primary btn-sm" do %>
					<i class="fad fa-plus-circle"></i>
					<%= "Add a New Address for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name %>
				<% end %>
				<!-- New Button -->

			</div>
			<!-- Panel - Body -->

		</div>
		<!-- Panel -->

	</div>
</div>
<!-- Page Content -->

app/views/phcdevworks_members/member/addresses/new.html.erb
<!-- PHCTitleSEO Title Variables -->
<% phc_title "Member Address Manager" %>
<% phc_title_tagline "Create a New Address for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name %>
<% phc_breadcrumb_one link_to "Members List", phcdevworks_members.member_profiles_path %>
<% phc_breadcrumb_two link_to "Addresses for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name, phcdevworks_members.member_profile_addresses_path %>
<% phc_breadcrumb_three yield(:phc_title_tagline) %>
<!-- PHCTitleSEO Title Variables -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_two) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_three) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h2 class="page-header"><%= yield(:phc_title) %></h2>
<!-- Page Header -->

<!-- Page Content -->
<div class="row">
	<div class="col-lg-12">

		<!-- Panel -->
		<div class="panel panel-inverse">

			<!-- Panel - Heading -->
			<div class="panel-heading">
				<h4 class="panel-title"><%= yield(:phc_title) %></h4>
			</div>
			<!-- Panel - Heading -->

			<!-- Panel - Body -->
			<div class="panel-body">

				<!-- New Form -->
				<%= render "form", { form_url: member_profile_addresses_path } %>
				<!-- New Form -->

			</div>
			<!-- Panel - Body -->

		</div>
		<!-- Panel -->

	</div>
</div>
<!-- Page Content -->

app/views/phcdevworks_members/member/addresses/show.html.erb
<!-- Title Variables -->
<% phc_title "Member Address Manager" %>
<% phc_title_tagline "Detailed Address Information for " + @member_profile.profile_first_name + " " + @member_profile.profile_last_name %>
<% phc_breadcrumb_one link_to "Members List", phcdevworks_members.member_profiles_path %>
<% phc_breadcrumb_two link_to "Addresses for " + @member_profile.profile_first_name + " " + @member_profile.profile_last_name, phcdevworks_members.member_profile_addresses_path %>
<% phc_breadcrumb_three yield(:phc_title_tagline) %>
<!-- Title System -->

<!-- Page Bradcrumbs -->
<ol class="breadcrumb pull-right">
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_one) %></li>
	<li class="breadcrumb-item"><%= yield(:phc_breadcrumb_two) %></li>
	<li class="breadcrumb-item active"><%= yield(:phc_breadcrumb_three) %></li>
</ol>
<!-- Page Bradcrumbs -->

<!-- Page Header -->
<h1 class="page-header"><%= yield(:phc_title) %></h1>
<!-- Page Header -->

<!-- Page Content -->
<div class="row">

	<!-- Address Information -->
	<div class="col-12">
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<div class="panel-heading-btn">
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
				</div>
				<h4 class="panel-title"><%= @member_profile.profile_first_name + " " + @member_profile.profile_last_name %> Address Details</h4>
			</div>
			<div class="panel-body">
				<!-- Table - Members Address -->
				<%= render 'phcdevworks_members/member/addresses/components/address_main' %>
				<!-- Table - Members Address -->
			</div>
		</div>
	</div>
	<!-- Address Information -->

	<!-- Address Information -->
	<div class="col-12">
		<div class="panel panel-inverse">
			<div class="panel-heading">
				<div class="panel-heading-btn">
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
					<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
				</div>
				<h4 class="panel-title"><%= @member_profile.profile_first_name + " " + @member_profile.profile_last_name %> Address Change Log</h4>
			</div>
			<div class="panel-body">
				<!-- Table - Members Address Audit -->
				<%= render 'phcdevworks_members/member/addresses/components/address_audits_table' %>
				<!-- Table - Members Address Audit -->
			</div>
		</div>
	</div>
	<!-- Address Information -->

</div>
<!-- Page Content -->