config/routes.rb
PhcdevworksMembers::Engine.routes.draw do

  # Dashboard Routes
  get 'dashboard', to: 'info/dashboard#index'

  # Member Routes
  namespace :member do
    resources :profiles, class_name: 'Member::Profile' do
      resources :listings, class_name: 'Member::Listing'
      resources :addresses, class_name: 'Member::Address'
    end
  end

  # Directory Routes
  namespace :directory do
    resources :categories, class_name: 'Directory::Category'
  end

  # API Routes
  namespace :api, :path => "", :constraints => {:subdomain => "api"} do
    namespace :v1 do
        resources :categories, defaults: {format: 'json'} do
        resources :listings, defaults: {format: 'json'}
      end
    end
  end

  # Mount Routes
  mount PhcdevworksAccounts::Engine, :at => '/'
  mount PhcdevworksCoreModules::Engine, :at => '/'

end

app/models/phcdevworks_members/member/listing.rb
module PhcdevworksMembers
  class Member::Listing < ApplicationRecord

    # Clean URL Initialize
    extend FriendlyId

    # Paper Trail Initialize
    has_paper_trail :class_name => "PhcdevworksMembers::MemberListingVersions"

    # Relationships
    belongs_to :profile, class_name: "PhcdevworksMembers::Member::Profile"
    belongs_to :optimization, class_name: "PhcdevworksCoreModules::Marketing::Optimization", optional: true
    has_and_belongs_to_many :categories, class_name: "PhcdevworksMembers::Directory::Category", :join_table => "phcdevworks_members_categories_lstings", :dependent => :destroy

    # Form Fields Validation
    validates :member_listing_company_name,
      presence: true

    validates :member_listing_contact_name,
      presence: true

    validates :member_listing_address_line_1,
      presence: true

    validates :member_listing_city,
      presence: true

    validates :member_listing_country,
      presence: true

    validates :member_listing_province,
      presence: true

    validates :member_listing_postal_code,
      presence: true

    validates :member_listing_contact_email,
      presence: true,
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Please follow this Email format: *****@********.***" }

    validates :member_listing_website,
      presence: true,
      format: { with: URI::regexp(%w(http https)), message: "Please follow this URL format http or https://www.**********.com" }

    validates :member_listing_phone,
      presence: true,
      format: { with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "Please Follow this Phone Member Format: ***-***-****" }

    # Clean URL Define
    friendly_id :members_listing_nice_urls, use: [:slugged, :finders]

    def members_listing_nice_urls
      [
        [:member_listing_company_name, :member_listing_contact_name]
      ]
    end

  end
end

app/controllers/phcdevworks_members/api/v1/listings_controller.rb
require_dependency "phcmembers/application_controller"

module Phcmembers
  class Api::V1::ListingsController < ApplicationController

    # Only Responds to API
    skip_before_action :phcmembers_get_member_profile_info
    respond_to :json

    # Directory Listing API
    def index
      category = Directory::Category.find(params[:category_id])
      @member_listings = category.listings.where(org_id: current_user.org_id).order('listing_company_name ASC')
    end

  end
end

app/controllers/phcdevworks_members/member/listings_controller.rb
require_dependency "phcdevworks_members/application_controller"

module PhcdevworksMembers
  class Member::ListingsController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_member_listing, only: [:show, :edit, :update, :destroy]

    # GET /member/listings
    # GET /member/listings.json
    def index
      @member_listings = member_profile.listings.all
    end

    # GET /member/listings/1
    # GET /member/listings/1.json
    def show
      @meber_listing = member_profile.listings.find(params[:id])
      @member_listing_versions = PhcdevworksMembers::MemberListingVersions.where(item_id: @member_listing, item_type: 'PhcdevworksMembers::Member::Listing')
    end

    # GET /member/listings/new
    def new
      @member_listing = member_profile.listings.build
    end

    # GET /member/listings/1/edit
    def edit
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
    end

    # POST /member/listings
    # POST /member/listings.json
    def create
      @member_listing = member_profile.listings.create(member_listing_params)
      @member_listing.user_id = current_user.id
      @member_listing.org_id = current_user.org_id
      respond_to do |format|
        if @member_listing.save
          format.html { redirect_to member_profile_listings_url, :flash => { :success => 'Member Listing has been Added' }}
          format.json { render :show, status: :created, location: @member_listing }
        else
          format.html { render :new }
          format.json { render json: @member_listing.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /member/listings/1
    # PATCH/PUT /member/listings/1.json
    def update
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
      respond_to do |format|
        if @member_listing.update(member_listing_params)
          format.html { redirect_to member_profile_listings_url, :flash => { :notice => 'Member Listing has been Updated.' }}
          format.json { render :show, status: :ok, location: @member_listing }
        else
          format.html { render :edit }
          format.json { render json: @member_listing.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /member/listings/1
    # DELETE /member/listings/1.json
    def destroy
      @member_listing = member_profile.listings.find(params[:id])
      @member_listing.destroy
      respond_to do |format|
        format.html { redirect_to member_profile_listings_url, :flash => { :error => 'Member Listing has been Removed' }}
        format.json { head :no_content }
      end
    end

    private

    # Common Callbacks
    def set_member_listing
     @member_listing = Member::Listing.friendly.find(params[:id])
    end

    def member_profile
      @member_profile = Member::Profile.friendly.find(params[:profile_id])
    end

    # Whitelist
    def member_listing_params
      params.require(:member_listing).permit(:member_listing_company_name, :member_listing_contact_name, :member_listing_address_line_1, :member_listing_address_line_2, :member_listing_city, :member_listing_country, :member_listing_province, :member_listing_postal_code, :member_listing_phone, :member_listing_contact_email, :member_listing_website, :profile_id, :slug, :user_id, :org_id, category_ids: [])
    end

  end
end

app/helpers/phcdevworks_members/member/listings_helper.rb
module PhcdevworksMembers
  module Member::ListingsHelper
  end
end

app/views/phcdevworks_members/member/listings/components/_listing_audits_table.html.erb
<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover">
		<tbody>
			<% @member_listing_versions.each do |member_listing_version| %>
				<tr>
					<td><span class="label label-primary"><%= member_listing_version.event.humanize %></span></td>
					<td><small>LISTING EVENT ID#<%= member_listing_version.id %></small></td>
					<td><%= member_listing_version.event.humanize + ' ' + @member_profile.member_profile_first_name + ' ' + @member_profile.member_profile_last_name %> Listing Information</td>
					<td><%= member_listing_version.whodunnit %></td>
					<td><%= l(member_listing_version.created_at, format: "%-d/%m/%Y") %> - <%= l(member_listing_version.created_at, format: "%H:%M %Z") %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/phcdevworks_members/member/listings/components/_listing_main.html.erb
<div class="row">
	<div class="col-6">
		<address class="m-t-5 m-b-5">
			<div><strong class="text-inverse"><%= @member_listing.member_listing_company_name %></strong></div>
			<div><strong class="text-inverse"><%= @member_listing.member_listing_contact_name %></strong></div>
			<div><%= @member_listing.member_listing_address_line_1 %></div>
			<div><%= @member_listing.member_listing_address_line_2 %></div>
			<div><%= @member_listing.member_listing_city %> <%= @member_listing.member_listing_province %></div>
			<div><%= @member_listing.member_listing_country %> <%= @member_listing.member_listing_postal_code %></div>
		</address>
	</div>
	<div class="col-6">
		Phone: <%= @member_listing.member_listing_phone %><br>
		Email: <%= @member_listing.member_listing_contact_email %><br>
		Website: <%= @member_listing.member_listing_website %><br>
	</div>
</div>
<br>
<div class="btn-group d-flex" role="group">
	<%= link_to 'Update', edit_member_profile_listing_path, class: "btn btn-purple btn-xs" %>
	<%= link_to 'Remove', member_profile_listing_path, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure? This will remove listing information and cannot be reversed.' } %>
</div>