config/routes.rb
PhcdevworksMembers::Engine.routes.draw do

  # Dashboard Routes
  get 'dashboard', to: 'info/dashboard#index'

  # Member Routes
  namespace :member do
    resources :profiles, class_name: 'Member::Profile' do
      resources :listings, class_name: 'Member::Listing'
      resources :addresses, class_name: 'Member::Address'
    end
  end

  # Directory Routes
  namespace :directory do
    resources :categories, class_name: 'Directory::Category'
  end

  # API Routes
  namespace :api, :path => "", :constraints => {:subdomain => "api"} do
    namespace :v1 do
        resources :categories, defaults: {format: 'json'} do
        resources :listings, defaults: {format: 'json'}
      end
    end
  end

  # Mount Routes
  mount PhcdevworksAccounts::Engine, :at => '/'
  mount PhcdevworksCoreModules::Engine, :at => '/'

end

app/models/phcdevworks_members/member/profile.rb
module PhcdevworksMembers
  class Member::Profile < ApplicationRecord

    # Clean URL Initialize
    extend FriendlyId

    # Paper Trail Initialize
    has_paper_trail :class_name => 'PhcdevworksMembers::MemberProfileVersions'

    # Profile Gravatar
    include Gravtastic
      gravtastic :member_profile_email

    # Relationships
    has_many :addresses, class_name: 'Member::Address', :dependent => :destroy
    has_many :listings, class_name: 'Member::Listing', :dependent => :destroy

    # Form Fields Validation
    validates :member_profile_first_name,
      presence: true

    validates :member_profile_last_name,
      presence: true

    validates :member_profile_title,
      presence: true

    validates :member_profile_email,
      presence: true,
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Please follow this Email format: *****@********.***" }

    validates :member_profile_phone,
      presence: true,
      format: { with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "Please Follow this Phone Number Format: ***-***-****" }

    # Clean URL Define
    friendly_id :members_profile_nice_urls, use: [:slugged, :finders]

    def members_profile_nice_urls
      [
        [:member_profile_first_name, :member_profile_last_name]
      ]
    end

  end
end

app/controllers/phcdevworks_members/member/profiles_controller.rb
require_dependency "phcdevworks_members/application_controller"

module PhcdevworksMembers
  class Member::ProfilesController < ApplicationController

    # Filters & Security
    #include PhcdevworksCore::PhcpluginsHelper
    before_action :authenticate_user!
    before_action :set_paper_trail_whodunnit
    before_action :set_member_profile, only: [:show, :edit, :update, :destroy]
    layout "phcdevworks_members/member_profile", :only => [ :show ]

    # GET /member/profiles
    # GET /member/profiles.json
    def index
      @member_profiles = Member::Profile.all
    end

    # GET /member/profiles/1
    # GET /member/profiles/1.json
    def show
      @member_profile_versions = PhcdevworksMembers::MemberProfileVersions.where(item_id: @member_profile, item_type: 'PhcdevworksMembers::Member::Profile')
    end

    # GET /member/profiles/new
    def new
      @member_profile = Member::Profile.new
    end

    # GET /member/profiles/1/edit
    def edit
    end

    # POST /member/profiles
    # POST /member/profiles.json
    def create
      @member_profile = Member::Profile.new(member_profile_params)
      @member_profile.user_id = current_user.id
      @member_profile.org_id = current_user.org_id
      respond_to do |format|
        if @member_profile.save
          format.html { redirect_to @member_profile, :flash => { :success => 'Member Profile has been Added.' }}
          format.json { render :show, status: :created, location: @member_profile }
        else
          format.html { render :new }
          format.json { render json: @member_profile.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /member/profiles/1
    # PATCH/PUT /member/profiles/1.json
    def update
      respond_to do |format|
        if @member_profile.update(member_profile_params)
          format.html { redirect_to @member_profile, :flash => { :notice => 'Member Profile has been Updated.' }}
          format.json { render :show, status: :ok, location: @member_profile }
        else
          format.html { render :edit }
          format.json { render json: @member_profile.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /member/profiles/1
    # DELETE /member/profiles/1.json
    def destroy
      @member_profile.destroy
      respond_to do |format|
        format.html { redirect_to member_profiles_url, :flash => { :error => 'Member Profile, Listings and Addresses have all been Removed.' }}
        format.json { head :no_content }
      end
    end

    private

    # Common Callbacks
    def set_member_profile
      @member_profile = Member::Profile.friendly.find(params[:id])
    end

    # Whitelist
    def member_profile_params
      params.require(:member_profile).permit(:member_profile_first_name, :member_profile_last_name, :member_profile_title, :member_profile_email, :member_profile_phone, :member_profile_notes, :slug, :user_id, :org_id)
    end

  end
end

app/helpers/phcdevworks_members/member/profiles_helper.rb
module PhcdevworksMembers
  module Member::ProfilesHelper
  end
end

app/views/phcdevworks_members/member/profiles/components/_profile_addresses_table.html.erb
<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th>Address Line 1</th>
				<th>City</th>
				<th>Province</th>
				<th>Type</th>
			</tr>
		</thead>
		<tbody>
			<% @member_profile.addresses.each do |members_main_address| %>
				<tr>
					<td><%= members_main_address.member_address_line_1 %></td>
					<td><%= members_main_address.member_address_city %></td>
					<td><%= members_main_address.member_address_province %></td>
					<td><%= members_main_address.member_address_type %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= link_to "See All of " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name + " Addresses", phcdevworks_members.member_profile_addresses_path(@member_profile), class: "btn btn-primary btn-xs" %>
	<%= link_to "Add a New Address for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name, phcdevworks_members.new_member_profile_address_path(@member_profile), class: "btn btn-purple btn-xs" %>
</div>

app/views/phcdevworks_members/member/profiles/components/_profile_audits_table.html.erb
<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover">
		<tbody>
			<% @member_profile_versions.each do |member_profile_version| %>
				<tr>
					<td><span class="label label-primary"><%= member_profile_version.event.humanize %></span></td>
					<td><small>PROFILE EVENT ID#<%= member_profile_version.id %></small></td>
					<td><%= member_profile_version.event.humanize + ' ' + @member_profile.member_profile_first_name + ' ' + @member_profile.member_profile_last_name %> Profile Information</td>
					<td><%= member_profile_version.whodunnit %></td>
					<td><%= l(member_profile_version.created_at, format: "%-d/%m/%Y") %> - <%= l(member_profile_version.created_at, format: "%H:%M %Z") %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/phcdevworks_members/member/profiles/components/_profile_header.html.erb
<div class="profile-header">

  <!-- Member Profiles - Header - Cover -->
  <div class="profile-header-cover"></div>
  <!-- Member Profiles - Header - Cover -->

  <!-- Member Profiles - Header - Content -->
  <div class="profile-header-content">
    <div class="profile-header-img">
      <%= image_tag @member_profile.gravatar_url :secure => true, :filetype => :png, :size => 128 %>
    </div>
    <div class="profile-header-info">
      <h4 class="m-t-10 m-b-5"><%= @member_profile.member_profile_first_name + ' ' + @member_profile.member_profile_last_name  %></h4>
      <p class="m-b-10"><%= @member_profile.member_profile_phone %></p>
      <%= link_to edit_member_profile_path(@member_profile), class: "btn btn-xs btn-yellow" do %>
        <i class="fad fa-user-edit"></i> Update Member Information
      <% end %>
    </div>
  </div>
  <!-- Member Profiles - Header - Content -->

  <!-- Member Profiles - Header - Tab Bar -->
  <ul class="profile-header-tab nav nav-tabs">
    <li class="nav-item"><a href="#profile-information" class="nav-link" data-toggle="tab">MEMBER INFORMATION</a></li>
    <li class="nav-item"><a href="#profile-addresses" class="nav-link" data-toggle="tab">MEMBER ADDRESSES</a></li>
    <li class="nav-item"><a href="#profile-listings" class="nav-link" data-toggle="tab">MEMBER LISTINGS</a></li>
    <li class="nav-item"><a href="#profile-logs" class="nav-link" data-toggle="tab">MEMBER CHANGE LOG</a></li>
  </ul>
  <!-- Member Profiles - Header - Tab Bar -->

</div>

app/views/phcdevworks_members/member/profiles/components/_profile_information_table.html.erb
<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Title</th>
				<th>Email</th>
				<th>Phone</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @member_profile.member_profile_first_name %></td>
				<td><%= @member_profile.member_profile_last_name %></td>
				<td><%= @member_profile.member_profile_title %></td>
				<td><%= @member_profile.member_profile_email %></td>
				<td><%= @member_profile.member_profile_phone %></td>
			</tr>
			<tr>
				<td><strong>Notes:</strong></td>
				<td colspan="4"><%= @member_profile.member_profile_notes %></td>
			</tr>
		</tbody>
	</table>
	<%= link_to "Update " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name + " Information", phcdevworks_members.edit_member_profile_path(@member_profile), class: "btn btn-primary btn-xs" %>
</div>

app/views/phcdevworks_members/member/profiles/components/_profile_listings_table.html.erb
<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th>Company Name</th>
				<th>Conact Name</th>
				<th>City</th>
				<th>Business Phone</th>
			</tr>
		</thead>
		<tbody>
			<% @member_profile.listings.each do |member_profile_listing| %>
				<tr>
					<td><%= member_profile_listing.member_listing_company_name %></td>
					<td><%= member_profile_listing.member_listing_contact_name %></td>
					<td><%= member_profile_listing.member_listing_city %></td>
					<td><%= member_profile_listing.member_listing_phone %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= link_to "See All of " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name + " Listings", phcdevworks_members.member_profile_listings_path(@member_profile), class: "btn btn-primary btn-xs" %>
	<%= link_to "Add a New Listing for " + @member_profile.member_profile_first_name + " " + @member_profile.member_profile_last_name, phcdevworks_members.new_member_profile_listing_path(@member_profile), class: "btn btn-purple btn-xs" %>
</div>